### ISSUE TITLE
"Cannot find module './'" error

### ISSUE THREAD

**Issue by Konfuze** [hemanth/head-it#1]
```
$ head-it --help
module.js:327
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/head-it/cli.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by hemanth** [comment]
Node version?

**Comment by Konfuze** [comment]
Sorry, node v4.4.5 @ os x 10.11, npm 2.15.5

Module was installed globally using sudo.

**Comment by hemanth** [comment]
Strange, it works well for me, for the same version and os combinations, but with `nvm`.

Can you change `/usr/local/lib/node_modules/head-it/cli.js` to `require('./index.js')` specifically and do you notice `index.js` in ``/usr/local/lib/node_modules/head-it/` ?

**Comment by Konfuze** [comment]
No, there's no `index.js` in `/usr/local/lib/node_modules/head-it/` folder:

```
$ ls
-rw-r--r--   1 nobody  staff   1,1K 31 май 16:04 license
-rwxr-xr-x   1 nobody  staff   432B 31 май 17:12 cli.js*
-rw-r--r--   1 nobody  staff    13K 31 май 17:16 head.js
-rw-r--r--   1 nobody  staff   1,1K 31 май 17:24 readme.md
-rw-r--r--   1 root    staff   1,6K  8 июн 12:03 package.json
drwxr-xr-x   3 nobody  staff   102B  8 июн 12:03 node_modules/
drwxr-xr-x  17 24561   wheel   578B  8 июн 12:03 ../
drwxr-xr-x   8 nobody  staff   272B  8 июн 12:03 ./
```

**Comment by hemanth** [comment]
I wonder why there is no `index.js` for you, the `package.json` has included all the [files](https://github.com/hemanth/head-it/blob/master/package.json#L19-L22) `npm link` on my local worked fine.

//cc @mklabs had you seen something like this before, `main` in mandatory?

**Comment by mklabs** [comment]
Sorry. Not sure I understand the issue here.

The main field is mandatory only if you want your package to be requirable, but I a agree it seems a bit weird.

Package name@version ?

**Comment by hemanth** [comment]
`head-it@1.0.1` seems like a `npm` bug?

**Comment by hemanth** [comment]
Looks like a [known issue](https://github.com/npm/npm/issues/5082) 

@Konfuze Can you confirm if it's working in the latest version?

**Comment by Konfuze** [comment]
@hemanth yes, it's 1.0.1

**Comment by hemanth** [comment]
@Konfuze No, the latest is `1.0.2`

**Comment by Konfuze** [comment]
@hemanth There's no `1.0.2` package:

```
npm install -g head-it@1.0.2
...
npm ERR! No compatible version found: head-it@1.0.2
npm ERR! Valid install targets:
npm ERR! 1.0.1, 1.0.0
```

**Comment by hemanth** [comment]
@Konfuze Yikes!

```
$ npm publish 
+ head-it@1.0.2
```

**Comment by Konfuze** [comment]
Yeah!

```
$head-it
Expected a string, one of: 360, min, elm, meta, link, fav, fbog, fbia, twitter, g+, oembed, ios, safari, android, chrome, ie, uc, qq, applinks
```

**Comment by hemanth** [comment]
Phew!
